# shellcheck shell=bash
# ============================================================================
# Atuin — shell history sync & search (overrides Ctrl+R from fzf)
# ----------------------------------------------------------------------------
# zz_ prefix pins this as one of the last-loaded modules so the Ctrl+R
# override wins over fzf (loaded earlier in modules/common/tools.sh).
# Source env first (adds ~/.atuin/bin to PATH), then init.
# ============================================================================

# shellcheck disable=SC1091  # optional env file generated by atuin installer
[[ -f "$HOME/.atuin/bin/env" ]] && . "$HOME/.atuin/bin/env"
if command -v atuin &> /dev/null; then
    # shellcheck disable=SC1090  # dynamic source from atuin init
    eval "$(atuin init zsh)"
fi
